# Generated by Django 5.2.6 on 2025-09-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_slog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slog',
            new_name='slug',
        ),
    ]
